### ISSUE TITLE
A means to iterate through a range of numbers in templates

### ISSUE THREAD

**Issue by cjvirtucio87** [pastdev/confd#7]
confd has an [lsdir](https://github.com/kelseyhightower/confd/blob/master/docs/templates.md) function which does the following:

>Returns all subkeys, []string, where path matches its argument. It only returns subkeys that also have subkeys. Returns an empty list if path is not found.

However, the subkeys are sorted [lexicographically](https://www.quora.com/What-is-lexicographic-order).

e.g. Given the following template:

```
{{- range $i := lsdir "/foo/objects"}}
object {{$i}} {{getv (printf "/foo/objects/%s/name" $i)}}
```

and the following configuration:

```
  objects:
  - name: first 
    address: '1234 Foo St.'
  - name: second 
    address: '1235 Foo St.
  - name: third 
    address: '1235 Foo St.'
  ...
  - name: eleventh 
    address: '1235 Foo St.
```

the following output results:

```
object 0 first
object 1 second
object 10 tenth
object 11 eleventh
object 2 third
```

I think it'd be helpful to include something similar to the `N` function from the [iter](https://godoc.org/github.com/bradfitz/iter) package that'd allow users to iterate through a range of numbers, and not worry about the lexicographical sorting. The above code could then be re-written as:

```
{{- range $i := N (len "/foo/objects")}}
object {{$i}} {{getv (printf "/foo/objects/%s/name" $i)}}
```

and we'd get the desired ordering:

```
object 0 first
object 1 second
object 2 third
...
object 10 tenth
object 11 eleventh
```
